metadata:
  title: ログ急増時の末尾抜粋表示 - 要件定義
  feature: log-tail-excerpt
  status: draft
  created: 2025-11-30
  updated: 2025-11-30
  version: "1.0.0"
  last_validated: null
  validation_passed: null
  complexity: small
  estimated-hours: 3
  dependencies: []

overview:
  description: ログ急増の通知時、行数だけでなく実際のログ末尾も数行添付することで、ユーザーが即座に問題の内容を把握できるようにする機能。

background:
  current-issues:
    - ログ急増の通知では「何行増えた」という情報のみ
    - 実際に何が起きているかを知るには、サーバーにログインしてログを確認する必要がある
    - 緊急時の初動が遅れる可能性
  
  goals:
    - 通知メッセージに実際のログ内容を含める
    - サーバーにログインせずに問題の概要を把握できる
    - 緊急度の判断を迅速に行える

acceptance-criteria:
  - id: AC-001
    title: ログ末尾の抽出
    priority: high
    description: |
      WHEN: ログ急増が検出された場合
      THEN: 該当ログファイルの末尾N行を抽出する
    details:
      - デフォルトは10行
      - 設定ファイルで行数を変更可能
      - ファイルが存在しない場合はエラーハンドリング
  
  - id: AC-002
    title: 通知メッセージへの追加
    priority: high
    description: |
      WHEN: ログ急増の通知を送信する場合
      THEN: 通知メッセージに末尾抜粋を含める
    details:
      - コードブロック形式で見やすく表示
      - ログファイルパスを明記
      - 抜粋であることを明示（「末尾10行」等）
  
  - id: AC-003
    title: 設定による制御
    priority: medium
    description: |
      WHEN: ユーザーが設定ファイルを編集した場合
      THEN: 末尾抜粋の表示行数を変更できる
    details:
      - log_analysis.tail_lines で設定
      - デフォルト値は10行
      - 0を指定した場合は末尾抜粋を無効化
  
  - id: AC-004
    title: 長い行の扱い
    priority: medium
    description: |
      WHEN: ログの1行が非常に長い場合
      THEN: 適切に切り詰めて表示する
    details:
      - 1行あたり最大500文字
      - 超過した場合は「... (truncated)」を追加
      - 通知メッセージが肥大化しないようにする
  
  - id: AC-005
    title: エラーハンドリング
    priority: high
    description: |
      WHEN: ログファイルの読み込みに失敗した場合
      THEN: エラーを記録し、末尾抜粋なしで通知を継続する
    details:
      - ファイルが存在しない
      - 読み込み権限がない
      - ファイルが空
      - これらの場合でも通知は送信される

non-functional-requirements:
  - id: NFR-001
    category: performance
    description: ログファイルの末尾読み込みは1秒以内。大きなログファイル（1GB以上）でも高速に動作
  
  - id: NFR-002
    category: compatibility
    description: 既存の通知機能に影響を与えない。設定を追加しない場合はデフォルト動作
  
  - id: NFR-003
    category: security
    description: ログに機密情報が含まれる可能性を考慮。設定で末尾抜粋を無効化できる

constraints:
  - ログファイルはテキスト形式のみ対応
  - バイナリログは非対応
  - ログローテーション中のファイルは考慮しない

success-criteria:
  - ログ急増通知に末尾抜粋が含まれる
  - 設定で行数を変更できる
  - 既存機能に影響がない
  - テストカバレッジ90%以上を維持
